CREATE DATABASE Productos;

USE Productos;

CREATE TABLE Producto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  imagen LONGBLOB NOT NULL,
  descripcion TEXT NOT NULL,
  precio DECIMAL(10, 2) NOT NULL,
  categoria VARCHAR(100) NOT NULL
);


